# Generated by Django 2.1.8 on 2019-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Id', models.AutoField(db_column='DepartmentId', primary_key=True, serialize=False)),
                ('DepartmentCode', models.CharField(db_column='DepartmentCode', max_length=50)),
                ('DepartmentName', models.CharField(db_column='DepartmentName', max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('Id', models.AutoField(db_column='DesignatioId', primary_key=True, serialize=False)),
                ('DesignatioCode', models.CharField(db_column='DesignatioCode', max_length=50)),
                ('DesignatioName', models.CharField(db_column='DesignatioName', max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'Designation',
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('UserId', models.CharField(db_column='UserId', max_length=255, unique=True)),
                ('UserName', models.CharField(db_column='UserName', max_length=255)),
                ('Password', models.CharField(db_column='Password', max_length=255)),
                ('Status', models.CharField(db_column='Status', default='Y', max_length=10)),
                ('StaffId', models.CharField(db_column='StaffId', max_length=100)),
                ('Mobile', models.CharField(db_column='Mobile', max_length=100)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, db_column='EntryDate')),
            ],
            options={
                'managed': False,
                'db_table': 'UserManager',
            },
        ),
    ]
